version: "3"

services:
  butler:
    container_name: butler
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - PORT=3000
    expose:
      - 3000
    command:
      - npm
      - run
      - watch:dev
    ports:
      - 3000:3000
    image: butler:latest
    volumes:
      - ./:/usr/src/app:cached
